version: "3.4"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  note-express:
    restart: always
    build: .
    image: note-express
    ports:
      - 8081:8081
    links:
      - mongo
    environment: 
      - NODE_ENV=container